using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Enzivor.Api.Migrations
{
    public partial class FixMissingLandfillReports : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // If old LandfillReports existed, rename; otherwise create UserReports.
            migrationBuilder.Sql(@"
DO $$
BEGIN
   IF to_regclass('public.""LandfillReports""') IS NOT NULL THEN
      ALTER TABLE ""LandfillReports"" RENAME TO ""UserReports"";
   ELSIF to_regclass('public.""UserReports""') IS NULL THEN
      CREATE TABLE ""UserReports"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ""Description"" text NULL,
        ""IsReviewed"" boolean NOT NULL DEFAULT FALSE,
        ""Latitude"" double precision NOT NULL,
        ""Longitude"" double precision NOT NULL,
        ""PlaceName"" text NULL,
        ""ReporterEmail"" text NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ""ReviewedAt"" timestamp with time zone NULL
      );
   END IF;
END $$;
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DO $$
BEGIN
   IF to_regclass('public.""UserReports""') IS NOT NULL
      AND to_regclass('public.""LandfillReports""') IS NULL THEN
      ALTER TABLE ""UserReports"" RENAME TO ""LandfillReports"";
   END IF;
END $$;
");
        }
    }
}
