using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Enzivor.Api.Migrations
{
    public partial class AddedUserMessageAndUserReportTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DO $$
BEGIN
   -- Case 1: legacy singular name
   IF to_regclass('public.""UserReport""') IS NOT NULL THEN
      -- Rename singular to plural
      ALTER TABLE ""UserReport"" RENAME TO ""UserReports"";
   -- Case 2: legacy LandfillReports name
   ELSIF to_regclass('public.""LandfillReports""') IS NOT NULL THEN
      -- Drop old PK if it exists (name may vary between envs)
      IF EXISTS (
         SELECT 1
         FROM pg_constraint
         WHERE conrelid = 'public.""LandfillReports""'::regclass
           AND conname = 'PK_LandfillReports'
      ) THEN
         ALTER TABLE ""LandfillReports"" DROP CONSTRAINT ""PK_LandfillReports"";
      END IF;

      -- Rename to the new name
      ALTER TABLE ""LandfillReports"" RENAME TO ""UserReports"";
   -- Case 3: fresh DB
   ELSIF to_regclass('public.""UserReports""') IS NULL THEN
      CREATE TABLE ""UserReports"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ""Description"" text NULL,
        ""IsReviewed"" boolean NOT NULL DEFAULT FALSE,
        ""Latitude"" double precision NOT NULL,
        ""Longitude"" double precision NOT NULL,
        ""PlaceName"" text NULL,
        ""ReporterEmail"" text NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ""ReviewedAt"" timestamp with time zone NULL
      );
   END IF;

   -- Ensure PK exists on UserReports after any path
   IF to_regclass('public.""UserReports""') IS NOT NULL THEN
      IF NOT EXISTS (
         SELECT 1
         FROM pg_constraint
         WHERE conrelid = 'public.""UserReports""'::regclass
           AND contype = 'p'
      ) THEN
         ALTER TABLE ""UserReports"" ADD CONSTRAINT ""PK_UserReports"" PRIMARY KEY (""Id"");
      END IF;
   END IF;
END $$;
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Best-effort rollback: rename back to singular if possible
            migrationBuilder.Sql(@"
DO $$
BEGIN
   IF to_regclass('public.""UserReports""') IS NOT NULL
      AND to_regclass('public.""UserReport""') IS NULL THEN
      -- Drop PK if named PK_UserReports (guarded)
      IF EXISTS (
         SELECT 1
         FROM pg_constraint
         WHERE conrelid = 'public.""UserReports""'::regclass
           AND conname = 'PK_UserReports'
      ) THEN
         ALTER TABLE ""UserReports"" DROP CONSTRAINT ""PK_UserReports"";
      END IF;

      ALTER TABLE ""UserReports"" RENAME TO ""UserReport"";

      -- (Optional) re-add PK name if needed
      IF NOT EXISTS (
         SELECT 1
         FROM pg_constraint
         WHERE conrelid = 'public.""UserReport""'::regclass
           AND contype = 'p'
      ) THEN
         ALTER TABLE ""UserReport"" ADD CONSTRAINT ""PK_UserReport"" PRIMARY KEY (""Id"");
      END IF;
   END IF;
END $$;
");
        }
    }
}
