// <auto-generated />
using System;
using Enzivor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enzivor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251022092735_AddStartYearToLandfillDetectionAndLandfillSite")]
    partial class AddStartYearToLandfillDetectionAndLandfillSite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enzivor.Api.Models.Domain.LandfillDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LandfillName")
                        .HasColumnType("text");

                    b.Property<int?>("LandfillSiteId")
                        .HasColumnType("integer");

                    b.Property<double>("NorthWestLat")
                        .HasColumnType("double precision");

                    b.Property<double>("NorthWestLon")
                        .HasColumnType("double precision");

                    b.Property<string>("PolygonCoordinates")
                        .HasColumnType("text");

                    b.Property<int?>("Region")
                        .HasColumnType("integer");

                    b.Property<string>("RegionTag")
                        .HasColumnType("text");

                    b.Property<double>("SouthEastLat")
                        .HasColumnType("double precision");

                    b.Property<double>("SouthEastLon")
                        .HasColumnType("double precision");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.Property<double>("SurfaceArea")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageName");

                    b.HasIndex("LandfillSiteId");

                    b.ToTable("LandfillDetections");
                });

            modelBuilder.Entity("Enzivor.Api.Models.Domain.LandfillSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoundaryGeoJson")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("EstimatedAreaM2")
                        .HasColumnType("double precision");

                    b.Property<double?>("EstimatedCH4TonsPerYear")
                        .HasColumnType("double precision");

                    b.Property<double?>("EstimatedCO2eTonsPerYear")
                        .HasColumnType("double precision");

                    b.Property<double?>("EstimatedDensity")
                        .HasColumnType("double precision");

                    b.Property<double?>("EstimatedDepth")
                        .HasColumnType("double precision");

                    b.Property<double?>("EstimatedMSW")
                        .HasColumnType("double precision");

                    b.Property<double?>("EstimatedVolumeM3")
                        .HasColumnType("double precision");

                    b.Property<double?>("MCF")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double?>("PointLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("PointLon")
                        .HasColumnType("double precision");

                    b.Property<int?>("Region")
                        .HasColumnType("integer");

                    b.Property<string>("RegionTag")
                        .HasColumnType("text");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("RegionTag");

                    b.ToTable("LandfillSites");
                });

            modelBuilder.Entity("Enzivor.Api.Models.Domain.UserMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserMessages");
                });

            modelBuilder.Entity("Enzivor.Api.Models.Domain.UserReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PlaceName")
                        .HasColumnType("text");

                    b.Property<string>("ReporterEmail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserReports");
                });

            modelBuilder.Entity("Enzivor.Api.Models.Domain.LandfillDetection", b =>
                {
                    b.HasOne("Enzivor.Api.Models.Domain.LandfillSite", "LandfillSite")
                        .WithMany("Detections")
                        .HasForeignKey("LandfillSiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LandfillSite");
                });

            modelBuilder.Entity("Enzivor.Api.Models.Domain.LandfillSite", b =>
                {
                    b.Navigation("Detections");
                });
#pragma warning restore 612, 618
        }
    }
}
